name: Snapshot Build Info

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CI: true
  JFROG_BUILD_STATUS: PASS
  JFROG_CLI_BUILD_NAME: ecosystem-build-info-dev
  JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
  JFROG_CLI_BUILD_PROJECT: ecosys

jobs:
  Snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "zulu"

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle-snapshot-${{ hashFiles('**/*.gradle', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-snapshot-

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: Configure JFrog CLI
        run: |
          jf c rm --quiet
          jf c add internal --url="$ARTIFACTORY_URL" --user="$ARTIFACTORY_USER" --password="$ARTIFACTORY_APIKEY"
          jf gradlec --use-wrapper --uses-plugin --repo-resolve ecosys-maven-remote --repo-deploy ecosys-oss-snapshot-local
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_APIKEY: ${{ secrets.ARTIFACTORY_APIKEY }}

      - name: Run audit
        run: jf audit --fail=false

      # Delete former snapshots to make sure the release bundle will not contain stale artifacts
      - name: Delete former snapshots
        run: jf rt del "ecosys-oss-snapshot-local/org/jfrog/buildinfo/*" --quiet

      - name: Build and publish to Artifactory
        run: jf gradle clean aP -x test

      - name: Publish build info
        run: |
          jf rt bag && jf rt bce
          jf rt bp

      - name: Distribute release bundle
        run: |
          jf ds rbc ecosystem-build-info-snapshot ${{ github.run_number }} --spec=./release/specs/dev-rbc-filespec.json --sign
          jf ds rbd ecosystem-build-info-snapshot ${{ github.run_number }} --site="releases.jfrog.io" --sync
